version: '3.5'

services:
  php:
    build:
      context: ./docker/php
    ports:
      - 9000:9000
    volumes:
      - ./site/:/var/www/html
      - ./docker/php/www.conf:/usr/local/etc/php-fpm.d/www.conf
      - ./migrations:/opt/scripts/migrations

  nginx:
    image: nginx:1.15
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./site/:/var/www/html
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./docker/ssl:/etc/ssl
    depends_on:
      - php
    networks:
      default:
        aliases:
          - tchatchao

  mysql:
    image: mysql:5.7
    ports:
      - 3306:3306
    volumes:
      - ./data/db:/var/lib/mysql
      - ./docker/mysql/my.cnf:/etc/mysql/conf.d/my.cnf
    depends_on:
      - php
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - 8888:80
    environment:
      PMA_ARBITRARY: 1
    depends_on:
      - mysql
    networks:
      default:
        aliases:
          - phpmyadmin

networks:
  default:
    name: local