vich_uploader:
    db_driver: orm

    mappings:
        members:
            uri_prefix: /images/members
            upload_destination: '%kernel.project_dir%/public/images/members'

            inject_on_load: false
            delete_on_update: true
            delete_on_remove: true

        events:
            uri_prefix: /images/events
            upload_destination: '%kernel.project_dir%/public/images/events'

            inject_on_load: false
            delete_on_update: true
            delete_on_remove: true

        albums:
            uri_prefix: /images/albums
            upload_destination: '%kernel.project_dir%/public/images/albums'

            inject_on_load: false
            delete_on_update: true
            delete_on_remove: true

        videos:
            uri_prefix: /images/videos
            upload_destination: '%kernel.project_dir%/public/images/videos'

            inject_on_load: false
            delete_on_update: true
            delete_on_remove: true

        backgrounds:
            uri_prefix: /images/backgrounds
            upload_destination: '%kernel.project_dir%/public/images/backgrounds'

            inject_on_load: false
            delete_on_update: true
            delete_on_remove: true