vich_uploader:
    db_driver: orm

    mappings:
        members:
            uri_prefix: /images/members
            upload_destination: '%kernel.project_dir%/public/images/members'

            inject_on_load: false
            delete_on_update: true
            delete_on_remove: true